### ISSUE TITLE
Typo in repo description, unforgivable 

### ISSUE THREAD

**Issue by Rei-x** [mikolajkapica/ram-schedulers#1]
> Excerice for my operating systems class – processor access scheduling algorithms 

Excerice? you want some sushi or what?

Fix your description in this repo please

**Comment by mikolajkapica** [comment]
Don't have to be so brutal

**Comment by mikolajkapica** [comment]
> > Excerice for my operating systems class – processor access scheduling algorithms 
> 
> Excerice? you want some sushi or what?
> 
> Fix your description in this repo please

Don't have to be so brutal
